/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WorkspaceWeatherRouteImport } from './routes/_workspace.weather'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceReportsRouteImport } from './routes/_workspace.reports'
import { Route as WorkspaceMarketIntelligenceRouteImport } from './routes/_workspace.market-intelligence'
import { Route as WorkspaceFarmProfileRouteImport } from './routes/_workspace.farm-profile'
import { Route as WorkspaceFarmPlannerRouteImport } from './routes/_workspace.farm-planner'
import { Route as WorkspaceDiseaseScannerRouteImport } from './routes/_workspace.disease-scanner'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceCommandCenterRouteImport } from './routes/_workspace.command-center'
import { Route as WorkspaceChatRouteImport } from './routes/_workspace.chat'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWeatherRoute = WorkspaceWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceReportsRoute = WorkspaceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceMarketIntelligenceRoute =
  WorkspaceMarketIntelligenceRouteImport.update({
    id: '/market-intelligence',
    path: '/market-intelligence',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceFarmProfileRoute = WorkspaceFarmProfileRouteImport.update({
  id: '/farm-profile',
  path: '/farm-profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceFarmPlannerRoute = WorkspaceFarmPlannerRouteImport.update({
  id: '/farm-planner',
  path: '/farm-planner',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDiseaseScannerRoute = WorkspaceDiseaseScannerRouteImport.update({
  id: '/disease-scanner',
  path: '/disease-scanner',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCommandCenterRoute = WorkspaceCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceChatRoute = WorkspaceChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat': typeof WorkspaceChatRoute
  '/command-center': typeof WorkspaceCommandCenterRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/disease-scanner': typeof WorkspaceDiseaseScannerRoute
  '/farm-planner': typeof WorkspaceFarmPlannerRoute
  '/farm-profile': typeof WorkspaceFarmProfileRoute
  '/market-intelligence': typeof WorkspaceMarketIntelligenceRoute
  '/reports': typeof WorkspaceReportsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/weather': typeof WorkspaceWeatherRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat': typeof WorkspaceChatRoute
  '/command-center': typeof WorkspaceCommandCenterRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/disease-scanner': typeof WorkspaceDiseaseScannerRoute
  '/farm-planner': typeof WorkspaceFarmPlannerRoute
  '/farm-profile': typeof WorkspaceFarmProfileRoute
  '/market-intelligence': typeof WorkspaceMarketIntelligenceRoute
  '/reports': typeof WorkspaceReportsRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/weather': typeof WorkspaceWeatherRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_workspace/chat': typeof WorkspaceChatRoute
  '/_workspace/command-center': typeof WorkspaceCommandCenterRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/disease-scanner': typeof WorkspaceDiseaseScannerRoute
  '/_workspace/farm-planner': typeof WorkspaceFarmPlannerRoute
  '/_workspace/farm-profile': typeof WorkspaceFarmProfileRoute
  '/_workspace/market-intelligence': typeof WorkspaceMarketIntelligenceRoute
  '/_workspace/reports': typeof WorkspaceReportsRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/weather': typeof WorkspaceWeatherRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/chat'
    | '/command-center'
    | '/dashboard'
    | '/disease-scanner'
    | '/farm-planner'
    | '/farm-profile'
    | '/market-intelligence'
    | '/reports'
    | '/settings'
    | '/weather'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/chat'
    | '/command-center'
    | '/dashboard'
    | '/disease-scanner'
    | '/farm-planner'
    | '/farm-profile'
    | '/market-intelligence'
    | '/reports'
    | '/settings'
    | '/weather'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_workspace/chat'
    | '/_workspace/command-center'
    | '/_workspace/dashboard'
    | '/_workspace/disease-scanner'
    | '/_workspace/farm-planner'
    | '/_workspace/farm-profile'
    | '/_workspace/market-intelligence'
    | '/_workspace/reports'
    | '/_workspace/settings'
    | '/_workspace/weather'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/weather': {
      id: '/_workspace/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WorkspaceWeatherRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/reports': {
      id: '/_workspace/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof WorkspaceReportsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/market-intelligence': {
      id: '/_workspace/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof WorkspaceMarketIntelligenceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/farm-profile': {
      id: '/_workspace/farm-profile'
      path: '/farm-profile'
      fullPath: '/farm-profile'
      preLoaderRoute: typeof WorkspaceFarmProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/farm-planner': {
      id: '/_workspace/farm-planner'
      path: '/farm-planner'
      fullPath: '/farm-planner'
      preLoaderRoute: typeof WorkspaceFarmPlannerRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/disease-scanner': {
      id: '/_workspace/disease-scanner'
      path: '/disease-scanner'
      fullPath: '/disease-scanner'
      preLoaderRoute: typeof WorkspaceDiseaseScannerRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/command-center': {
      id: '/_workspace/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof WorkspaceCommandCenterRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/chat': {
      id: '/_workspace/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof WorkspaceChatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceChatRoute: typeof WorkspaceChatRoute
  WorkspaceCommandCenterRoute: typeof WorkspaceCommandCenterRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceDiseaseScannerRoute: typeof WorkspaceDiseaseScannerRoute
  WorkspaceFarmPlannerRoute: typeof WorkspaceFarmPlannerRoute
  WorkspaceFarmProfileRoute: typeof WorkspaceFarmProfileRoute
  WorkspaceMarketIntelligenceRoute: typeof WorkspaceMarketIntelligenceRoute
  WorkspaceReportsRoute: typeof WorkspaceReportsRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceWeatherRoute: typeof WorkspaceWeatherRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceChatRoute: WorkspaceChatRoute,
  WorkspaceCommandCenterRoute: WorkspaceCommandCenterRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceDiseaseScannerRoute: WorkspaceDiseaseScannerRoute,
  WorkspaceFarmPlannerRoute: WorkspaceFarmPlannerRoute,
  WorkspaceFarmProfileRoute: WorkspaceFarmProfileRoute,
  WorkspaceMarketIntelligenceRoute: WorkspaceMarketIntelligenceRoute,
  WorkspaceReportsRoute: WorkspaceReportsRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceWeatherRoute: WorkspaceWeatherRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
